### ISSUE TITLE
[linux-error]undefined symbol: s_mp_rand_source

### ISSUE THREAD

**Issue by dtera** [libtom/libtommath#582]
I use libtommath in java, the error is as follows(it’s OK on mac os)：
```
xxx/linux-x86_64/libjniTommath.so: undefined symbol: s_mp_rand_source
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1779)
```

**Comment by levitte** [comment]
I looked at the source and found a case when this could happen.  See #583

**Comment by dtera** [comment]
> I looked at the source and found a case when this could happen. See #583
@levitte @sjaeckel The both of solutions above don't work. The same error is issued on Linux(it’s ok on Mac). By the way, this error is a runtime error, and there is no problem when compiling.

**Comment by dtera** [comment]
I tried to compile the source code with bazel and call it in java, and the problems above did not occur.

**Comment by sjaeckel** [comment]
I also thought, "maybe optimizing a bit too much" and removing the symbol even though it's still required.

How exactly did you produce the error?

**Comment by dtera** [comment]
> I also thought, "maybe optimizing a bit too much" and removing the symbol even though it's still required.
> 
> How exactly did you produce the 

[Repo] https://github.com/dtera/bazel_java
Before running the java test shown below, you should first run `mvn clean package` to generate the native library.
![image](https://github.com/user-attachments/assets/097b7a37-3694-409d-ba1d-ff87115ce0ad)
